import Head from 'next/head'
import { useEffect, useState } from 'react'
import axios from 'axios'
import { HUB_BASE_URL } from '@/constant'
import useTrans from './hooks/useTrans'


export default function Home() {
  const [test, setTest] = useState<any>([])
  useEffect(() => {
    axios.get(`${HUB_BASE_URL}/api/products`)
      .then(res => {
        setTest(res?.data?.products)
      })
  }, [])

  // const trans = useTrans()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='text-red-400'>đasadsadsad</div>
      {
        test?.map((data: any) => (
          <div key={data?._id}>{data?.inStock}</div>
        ))
      }
      {/* <h1>
        {trans.home.title}
      </h1> */}
    </>
  )
}
